global:
  resolve_timeout: 5m
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@loanwise.com'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical'
    - match:
        severity: warning
      receiver: 'warning'

receivers:
  - name: 'default'
    # Default receiver - no notifications configured yet

  - name: 'critical'
    # Critical alerts - configure email/slack when ready
    # webhook_configs:
    #   - url: 'http://localhost:5001/critical'

  - name: 'warning'
    # Warning alerts - configure email/slack when ready
    # webhook_configs:
    #   - url: 'http://localhost:5001/warning'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
