---
- name: Deploy LoanWise Application
  hosts: "{{ target_hosts | default('app_servers') }}"
  remote_user: ec2-user
  become: yes

  vars:
    docker_image: "{{ docker_image }}"
    environment: "{{ environment | default('production') }}"
    app_container_name: loanwise-app
    app_port: 8080

  pre_tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest
      tags: always

  tasks:
    - name: Install Docker
      yum:
        name:
          - docker
        state: present
      register: docker_install

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull latest Docker image
      shell: |
        docker pull "{{ docker_image }}"
      register: docker_pull
      changed_when: "'Pulling from' in docker_pull.stdout"

    - name: Stop running container
      shell: docker stop {{ app_container_name }} || true
      changed_when: false

    - name: Remove old container
      shell: docker rm {{ app_container_name }} || true
      changed_when: false

    - name: Run Docker container
      shell: |
        docker run -d \
          --name {{ app_container_name }} \
          --restart always \
          -p {{ app_port }}:8080 \
          -e DATABASE_URL="{{ database_url }}" \
          -e ENVIRONMENT="{{ environment }}" \
          {{ docker_image }}

    - name: Wait for application to be healthy
      shell: |
        for i in {1..12}; do
          if curl -f http://localhost:{{ app_port }} 2>/dev/null; then
            echo "Application is healthy"
            exit 0
          fi
          sleep 5
        done
        exit 1

  post_tasks:
    - name: Print deployment summary
      debug:
        msg:
          - "Application deployed successfully!"
          - "Image: {{ docker_image }}"
          - "Container: {{ app_container_name }}"
          - "Port: {{ app_port }}"
          - "Environment: {{ environment }}"
