---
- name: Setup Grafana Dashboards
  hosts: "{{ target_hosts | default('monitoring') }}"
  remote_user: ec2-user
  become: yes
  
  vars:
    grafana_version: "10.2.2"
    grafana_port: 3000
    grafana_admin_user: admin
    grafana_admin_password: "{{ grafana_admin_password | default('admin123') }}"
  
  tasks:
    - name: Add Grafana repository
      copy:
        content: |
          [grafana]
          name=grafana
          baseurl=https://rpm.grafana.com
          repo_gpgcheck=1
          enabled=1
          gpgcheck=1
          gpgkey=https://rpm.grafana.com/RPM-GPG-KEY-grafana
          sslverify=1
          sslcacert=/etc/pki/tls/certs/ca-bundle.crt
        dest: /etc/yum.repos.d/grafana.repo
    
    - name: Install Grafana
      yum:
        name: grafana
        state: present
    
    - name: Create Grafana provisioning directories
      file:
        path: "{{ item }}"
        state: directory
        owner: grafana
        group: grafana
        mode: '0755'
      loop:
        - /etc/grafana/provisioning/datasources
        - /etc/grafana/provisioning/dashboards
    
    - name: Configure Grafana datasource (Prometheus)
      copy:
        content: |
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://localhost:9090
              isDefault: true
              editable: true
        dest: /etc/grafana/provisioning/datasources/prometheus.yaml
        owner: grafana
        group: grafana
        mode: '0644'
    
    - name: Configure Grafana dashboard provider
      copy:
        content: |
          apiVersion: 1
          providers:
            - name: 'Default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              updateIntervalSeconds: 10
              allowUiUpdates: true
              options:
                path: /var/lib/grafana/dashboards
        dest: /etc/grafana/provisioning/dashboards/dashboards.yaml
        owner: grafana
        group: grafana
        mode: '0644'
    
    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes
        daemon_reload: yes
    
    - name: Wait for Grafana to be ready
      uri:
        url: "http://localhost:{{ grafana_port }}/api/health"
        method: GET
        status_code: 200
      register: result
      until: result.status == 200
      retries: 12
      delay: 5
    
    - name: Set Grafana admin password
      grafana_admin_user:
        grafana_url: "http://localhost:{{ grafana_port }}"
        grafana_api_key: "{{ lookup('password', '/tmp/grafana_api_key') }}"
        state: present
        login_user: "{{ grafana_admin_user }}"
        login_password: admin
        new_password: "{{ grafana_admin_password }}"
      ignore_errors: yes
    
    - name: Create performance dashboard
      grafana_dashboard:
        grafana_url: "http://localhost:{{ grafana_port }}"
        grafana_api_key: "{{ lookup('password', '/tmp/grafana_api_key') }}"
        state: present
        dashboard: "{{ lookup('file', 'dashboards/performance.json') }}"
      ignore_errors: yes
    
    - name: Print Grafana access information
      debug:
        msg:
          - "Grafana has been installed successfully!"
          - "Access URL: http://localhost:{{ grafana_port }}"
          - "Admin User: {{ grafana_admin_user }}"
          - "Data Source: Prometheus (http://localhost:9090)"
