name: Auto Label PRs

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Auto-label based on files changed
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml

    - name: Label based on PR size
      uses: pascalgn/size-label-action@v0.4.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        sizes: >
          {
            "0": "XS",
            "20": "S",
            "50": "M",
            "200": "L",
            "800": "XL",
            "2000": "XXL"
          }

    - name: Label based on branch name
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo, number } = context.issue;
          const branchName = context.payload.pull_request.head.ref;

          const labels = [];

          if (branchName.startsWith('feature/')) {
            labels.push('enhancement');
          } else if (branchName.startsWith('fix/') || branchName.startsWith('bugfix/')) {
            labels.push('bug');
          } else if (branchName.startsWith('docs/')) {
            labels.push('documentation');
          } else if (branchName.startsWith('refactor/')) {
            labels.push('refactor');
          } else if (branchName.startsWith('test/')) {
            labels.push('tests');
          } else if (branchName.startsWith('chore/')) {
            labels.push('maintenance');
          }

          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: number,
              labels
            });
          }
